// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileUploadTest.Model
{
    public partial class Tblfileupload
    {
        public int ImageId { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
    }
}