// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using FileUploadTest.Model;

namespace FileUploadTest.Data
{
    public partial class FirstDBContext : DbContext
    {
        public FirstDBContext()
        {
        }

        public FirstDBContext(DbContextOptions<FirstDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Tblfileupload> Tblfileuploads { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Tblfileupload>(entity =>
            {
                entity.HasKey(e => e.ImageId);

                entity.ToTable("tblfileupload");
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}